version: '3.8'

services:
  mysql:
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306

  postgres:
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
